[package]
name = "font"
version = "0.4.2"
edition = "2021"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides a font toolbox."
documentation = "https://docs.rs/font"
homepage = "https://github.com/bodoni/font"
repository = "https://github.com/bodoni/font"
exclude = ["tests/fixtures/*"]

[dependencies]
opentype = "0.19"
postscript = "0.14"
truetype = "0.31"

[dev-dependencies]
svg = "0.9"
