[package]
name = "font"
version = "0.10.7"
edition = "2021"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides a parser for fonts."
documentation = "https://docs.rs/font"
homepage = "https://github.com/bodoni/font"
repository = "https://github.com/bodoni/font"
exclude = ["tests/fixtures/*"]

[dependencies]
opentype = "0.24.7"
postscript = "0.17.1"
truetype = "0.41.0"
typeface = "0.2.4"
