#[macro_use]
mod support;

use std::ops::RangeInclusive;

use font::opentype::truetype::Tag;
use font::Font;

use crate::support::{setup, Fixture};

#[test]
fn crimson_text() {
    let mut file = setup(Fixture::CrimsonText);
    let entries = extract(&mut file[0]);
    let entries = entries
        .iter()
        .map(|(feature, script, language, _)| (&**feature, &**script, &**language))
        .collect::<Vec<_>>();
    assert_eq!(
        entries,
        [
            ("case", "DFLT", "DFLT"),
            ("case", "latn", "AZE "),
            ("case", "latn", "CAT "),
            ("case", "latn", "CRT "),
            ("case", "latn", "DFLT"),
            ("case", "latn", "KAZ "),
            ("case", "latn", "MOL "),
            ("case", "latn", "ROM "),
            ("case", "latn", "TAT "),
            ("case", "latn", "TRK "),
            ("ccmp", "DFLT", "DFLT"),
            ("ccmp", "latn", "AZE "),
            ("ccmp", "latn", "CAT "),
            ("ccmp", "latn", "CRT "),
            ("ccmp", "latn", "DFLT"),
            ("ccmp", "latn", "KAZ "),
            ("ccmp", "latn", "MOL "),
            ("ccmp", "latn", "ROM "),
            ("ccmp", "latn", "TAT "),
            ("ccmp", "latn", "TRK "),
            ("dlig", "DFLT", "DFLT"),
            ("dlig", "latn", "AZE "),
            ("dlig", "latn", "CAT "),
            ("dlig", "latn", "CRT "),
            ("dlig", "latn", "DFLT"),
            ("dlig", "latn", "KAZ "),
            ("dlig", "latn", "MOL "),
            ("dlig", "latn", "ROM "),
            ("dlig", "latn", "TAT "),
            ("dlig", "latn", "TRK "),
            ("dnom", "DFLT", "DFLT"),
            ("dnom", "latn", "AZE "),
            ("dnom", "latn", "CAT "),
            ("dnom", "latn", "CRT "),
            ("dnom", "latn", "DFLT"),
            ("dnom", "latn", "KAZ "),
            ("dnom", "latn", "MOL "),
            ("dnom", "latn", "ROM "),
            ("dnom", "latn", "TAT "),
            ("dnom", "latn", "TRK "),
            ("frac", "DFLT", "DFLT"),
            ("frac", "latn", "AZE "),
            ("frac", "latn", "CAT "),
            ("frac", "latn", "CRT "),
            ("frac", "latn", "DFLT"),
            ("frac", "latn", "KAZ "),
            ("frac", "latn", "MOL "),
            ("frac", "latn", "ROM "),
            ("frac", "latn", "TAT "),
            ("frac", "latn", "TRK "),
            ("kern", "DFLT", "DFLT"),
            ("kern", "latn", "DFLT"),
            ("liga", "DFLT", "DFLT"),
            ("liga", "latn", "AZE "),
            ("liga", "latn", "CAT "),
            ("liga", "latn", "CRT "),
            ("liga", "latn", "DFLT"),
            ("liga", "latn", "KAZ "),
            ("liga", "latn", "MOL "),
            ("liga", "latn", "ROM "),
            ("liga", "latn", "TAT "),
            ("liga", "latn", "TRK "),
            ("locl", "latn", "AZE "),
            ("locl", "latn", "CAT "),
            ("locl", "latn", "CRT "),
            ("locl", "latn", "KAZ "),
            ("locl", "latn", "MOL "),
            ("locl", "latn", "ROM "),
            ("locl", "latn", "TAT "),
            ("locl", "latn", "TRK "),
            ("mark", "DFLT", "DFLT"),
            ("mark", "latn", "DFLT"),
            ("mkmk", "DFLT", "DFLT"),
            ("mkmk", "latn", "DFLT"),
            ("numr", "DFLT", "DFLT"),
            ("numr", "latn", "AZE "),
            ("numr", "latn", "CAT "),
            ("numr", "latn", "CRT "),
            ("numr", "latn", "DFLT"),
            ("numr", "latn", "KAZ "),
            ("numr", "latn", "MOL "),
            ("numr", "latn", "ROM "),
            ("numr", "latn", "TAT "),
            ("numr", "latn", "TRK "),
            ("sinf", "DFLT", "DFLT"),
            ("sinf", "latn", "AZE "),
            ("sinf", "latn", "CAT "),
            ("sinf", "latn", "CRT "),
            ("sinf", "latn", "DFLT"),
            ("sinf", "latn", "KAZ "),
            ("sinf", "latn", "MOL "),
            ("sinf", "latn", "ROM "),
            ("sinf", "latn", "TAT "),
            ("sinf", "latn", "TRK "),
            ("subs", "DFLT", "DFLT"),
            ("subs", "latn", "AZE "),
            ("subs", "latn", "CAT "),
            ("subs", "latn", "CRT "),
            ("subs", "latn", "DFLT"),
            ("subs", "latn", "KAZ "),
            ("subs", "latn", "MOL "),
            ("subs", "latn", "ROM "),
            ("subs", "latn", "TAT "),
            ("subs", "latn", "TRK "),
            ("sups", "DFLT", "DFLT"),
            ("sups", "latn", "AZE "),
            ("sups", "latn", "CAT "),
            ("sups", "latn", "CRT "),
            ("sups", "latn", "DFLT"),
            ("sups", "latn", "KAZ "),
            ("sups", "latn", "MOL "),
            ("sups", "latn", "ROM "),
            ("sups", "latn", "TAT "),
            ("sups", "latn", "TRK "),
            ("zero", "DFLT", "DFLT"),
            ("zero", "latn", "AZE "),
            ("zero", "latn", "CAT "),
            ("zero", "latn", "CRT "),
            ("zero", "latn", "DFLT"),
            ("zero", "latn", "KAZ "),
            ("zero", "latn", "MOL "),
            ("zero", "latn", "ROM "),
            ("zero", "latn", "TAT "),
            ("zero", "latn", "TRK "),
        ]
    );
}

#[test]
fn noto_serif() {
    let mut file = setup(Fixture::NotoSerifThai);
    let entries = extract(&mut file[0]);
    let entries = entries
        .iter()
        .map(|(feature, script, language, _)| (&**feature, &**script, &**language))
        .collect::<Vec<_>>();
    assert_eq!(
        entries,
        [
            ("aalt", "cyrl", "DFLT"),
            ("aalt", "cyrl", "MKD "),
            ("aalt", "cyrl", "SRB "),
            ("aalt", "DFLT", "DFLT"),
            ("aalt", "grek", "APPH"),
            ("aalt", "grek", "DFLT"),
            ("aalt", "grek", "IPPH"),
            ("aalt", "latn", "APPH"),
            ("aalt", "latn", "CAT "),
            ("aalt", "latn", "DFLT"),
            ("aalt", "latn", "IPPH"),
            ("aalt", "latn", "MAH "),
            ("aalt", "latn", "MOL "),
            ("aalt", "latn", "NAV "),
            ("aalt", "latn", "ROM "),
            ("aalt", "thai", "DFLT"),
            ("ccmp", "cyrl", "DFLT"),
            ("ccmp", "cyrl", "MKD "),
            ("ccmp", "cyrl", "SRB "),
            ("ccmp", "DFLT", "DFLT"),
            ("ccmp", "grek", "APPH"),
            ("ccmp", "grek", "DFLT"),
            ("ccmp", "grek", "IPPH"),
            ("ccmp", "latn", "APPH"),
            ("ccmp", "latn", "CAT "),
            ("ccmp", "latn", "DFLT"),
            ("ccmp", "latn", "IPPH"),
            ("ccmp", "latn", "MAH "),
            ("ccmp", "latn", "MOL "),
            ("ccmp", "latn", "NAV "),
            ("ccmp", "latn", "ROM "),
            ("ccmp", "thai", "DFLT"),
            ("dist", "cyrl", "DFLT"),
            ("dist", "cyrl", "MKD "),
            ("dist", "cyrl", "SRB "),
            ("dist", "DFLT", "DFLT"),
            ("dist", "grek", "APPH"),
            ("dist", "grek", "DFLT"),
            ("dist", "grek", "IPPH"),
            ("dist", "latn", "APPH"),
            ("dist", "latn", "CAT "),
            ("dist", "latn", "DFLT"),
            ("dist", "latn", "IPPH"),
            ("dist", "latn", "MAH "),
            ("dist", "latn", "MOL "),
            ("dist", "latn", "NAV "),
            ("dist", "latn", "ROM "),
            ("dist", "thai", "DFLT"),
            ("kern", "DFLT", "DFLT"),
            ("kern", "latn", "APPH"),
            ("kern", "latn", "CAT "),
            ("kern", "latn", "DFLT"),
            ("kern", "latn", "IPPH"),
            ("kern", "latn", "MAH "),
            ("kern", "latn", "MOL "),
            ("kern", "latn", "NAV "),
            ("kern", "latn", "ROM "),
            ("kern", "thai", "DFLT"),
            ("liga", "cyrl", "DFLT"),
            ("liga", "cyrl", "MKD "),
            ("liga", "cyrl", "SRB "),
            ("liga", "DFLT", "DFLT"),
            ("liga", "grek", "APPH"),
            ("liga", "grek", "DFLT"),
            ("liga", "grek", "IPPH"),
            ("liga", "latn", "APPH"),
            ("liga", "latn", "CAT "),
            ("liga", "latn", "DFLT"),
            ("liga", "latn", "IPPH"),
            ("liga", "latn", "MAH "),
            ("liga", "latn", "MOL "),
            ("liga", "latn", "NAV "),
            ("liga", "latn", "ROM "),
            ("liga", "thai", "DFLT"),
            ("locl", "latn", "MOL "),
            ("locl", "latn", "ROM "),
            ("mark", "cyrl", "DFLT"),
            ("mark", "cyrl", "MKD "),
            ("mark", "cyrl", "SRB "),
            ("mark", "DFLT", "DFLT"),
            ("mark", "grek", "APPH"),
            ("mark", "grek", "DFLT"),
            ("mark", "grek", "IPPH"),
            ("mark", "latn", "APPH"),
            ("mark", "latn", "CAT "),
            ("mark", "latn", "DFLT"),
            ("mark", "latn", "IPPH"),
            ("mark", "latn", "MAH "),
            ("mark", "latn", "MOL "),
            ("mark", "latn", "NAV "),
            ("mark", "latn", "ROM "),
            ("mark", "thai", "DFLT"),
            ("mkmk", "cyrl", "DFLT"),
            ("mkmk", "cyrl", "MKD "),
            ("mkmk", "cyrl", "SRB "),
            ("mkmk", "DFLT", "DFLT"),
            ("mkmk", "grek", "APPH"),
            ("mkmk", "grek", "DFLT"),
            ("mkmk", "grek", "IPPH"),
            ("mkmk", "latn", "APPH"),
            ("mkmk", "latn", "CAT "),
            ("mkmk", "latn", "DFLT"),
            ("mkmk", "latn", "IPPH"),
            ("mkmk", "latn", "MAH "),
            ("mkmk", "latn", "MOL "),
            ("mkmk", "latn", "NAV "),
            ("mkmk", "latn", "ROM "),
            ("mkmk", "thai", "DFLT"),
            ("ordn", "cyrl", "DFLT"),
            ("ordn", "cyrl", "MKD "),
            ("ordn", "cyrl", "SRB "),
            ("ordn", "DFLT", "DFLT"),
            ("ordn", "grek", "APPH"),
            ("ordn", "grek", "DFLT"),
            ("ordn", "grek", "IPPH"),
            ("ordn", "latn", "APPH"),
            ("ordn", "latn", "CAT "),
            ("ordn", "latn", "DFLT"),
            ("ordn", "latn", "IPPH"),
            ("ordn", "latn", "MAH "),
            ("ordn", "latn", "MOL "),
            ("ordn", "latn", "NAV "),
            ("ordn", "latn", "ROM "),
            ("ordn", "thai", "DFLT"),
            ("ss01", "cyrl", "DFLT"),
            ("ss01", "cyrl", "MKD "),
            ("ss01", "cyrl", "SRB "),
            ("ss01", "DFLT", "DFLT"),
            ("ss01", "grek", "APPH"),
            ("ss01", "grek", "DFLT"),
            ("ss01", "grek", "IPPH"),
            ("ss01", "latn", "APPH"),
            ("ss01", "latn", "CAT "),
            ("ss01", "latn", "DFLT"),
            ("ss01", "latn", "IPPH"),
            ("ss01", "latn", "MAH "),
            ("ss01", "latn", "MOL "),
            ("ss01", "latn", "NAV "),
            ("ss01", "latn", "ROM "),
            ("ss01", "thai", "DFLT"),
        ]
    );
}

#[test]
fn qahiri() {
    let mut file = setup(Fixture::Qahiri);
    let entries = extract(&mut file[0]);
    let entries = entries
        .iter()
        .map(|(feature, script, language, _)| (&**feature, &**script, &**language))
        .collect::<Vec<_>>();
    assert_eq!(
        entries,
        [
            ("calt", "arab", "DFLT"),
            ("calt", "DFLT", "DFLT"),
            ("ccmp", "arab", "DFLT"),
            ("ccmp", "DFLT", "DFLT"),
            ("clig", "arab", "DFLT"),
            ("clig", "DFLT", "DFLT"),
            ("curs", "arab", "DFLT"),
            ("curs", "DFLT", "DFLT"),
            ("dnom", "arab", "DFLT"),
            ("dnom", "DFLT", "DFLT"),
            ("fina", "arab", "DFLT"),
            ("fina", "DFLT", "DFLT"),
            ("init", "arab", "DFLT"),
            ("init", "DFLT", "DFLT"),
            ("isol", "arab", "DFLT"),
            ("isol", "DFLT", "DFLT"),
            ("kern", "arab", "DFLT"),
            ("kern", "DFLT", "DFLT"),
            ("locl", "latn", "DFLT"),
            ("mark", "arab", "DFLT"),
            ("mark", "DFLT", "DFLT"),
            ("medi", "arab", "DFLT"),
            ("medi", "DFLT", "DFLT"),
            ("numr", "arab", "DFLT"),
            ("numr", "DFLT", "DFLT"),
            ("onum", "arab", "DFLT"),
            ("onum", "DFLT", "DFLT"),
            ("rclt", "arab", "DFLT"),
            ("rclt", "DFLT", "DFLT"),
            ("salt", "arab", "DFLT"),
            ("salt", "DFLT", "DFLT"),
            ("salt", "latn", "DFLT"),
            ("ss01", "arab", "DFLT"),
            ("ss01", "DFLT", "DFLT"),
            ("ss02", "arab", "DFLT"),
            ("ss02", "DFLT", "DFLT"),
        ]
    );
}

fn extract<T>(font: &mut Font<T>) -> Vec<(String, String, String, Vec<Vec<RangeInclusive<char>>>)>
where
    T: font::Read,
{
    ok!(font.features())
        .into_iter()
        .flat_map(|(feature, value)| {
            value.into_iter().flat_map(move |(script, value)| {
                value.into_iter().map(move |(language, characters)| {
                    (
                        ok!(Tag::from(feature.clone()).as_str()).to_string(),
                        ok!(Tag::from(script.clone()).as_str()).to_string(),
                        ok!(Tag::from(language).as_str()).to_string(),
                        characters,
                    )
                })
            })
        })
        .collect()
}
